### ISSUE TITLE
How to install stringer using docker-compose?

### ISSUE THREAD

**Issue by InfiniteCoder** [swanson/stringer#474]
I tried following [this one liner](https://github.com/swanson/stringer/blob/master/docs/docker.md#production-ready-setup-using-docker-compose) tutorial, but I can't figure out how to make it work.

I'm sure there's more to it than simply `docker-compose up -d`. When I run the quick test setup, it works fine, and I can access stringer via Internet, but it doesn't seem to work with the docker-compose.yml file.

My guess is that I should change `SECRET_TOKEN` and set `POSTGRES_PASSWORD` to some randomised string, but that doesn't seem to help.

**Comment by gabrielpoca** [comment]
Hi @InfiniteCoder I've pasted here pieces of my current docker-compose.yml.

Postgres:

```
  postgres:
    image: postgres:9.5-alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=asdf
      - POSTGRES_USER=asdf
      - POSTGRES_DB=stringer
```

Stringer:


```
stringer:
  image: mdswanson/stringer
  depends_on:
    - postgres
  restart: always
  environment:
    - SECRET_TOKEN=asdf
    - PORT=80
    - DATABASE_URL=postgres://asdf:asdf@postgres:5432/stringer
```

And volumes

```
volumes:
  postgres:
```

I hope it helps.
